### ISSUE TITLE
Feature request: sets of control variables

### ISSUE THREAD

**Issue by karldw** [masurp/specr#11]
When I'm considering which control variables to add, I'm often considering one set or another, not one variable at a time. Would you consider a syntax that supports sets of controls?

Another approach would be to consider every possible subset of `controls`, but the number of possible combinations increases pretty fast.

Here's an example:
``` r
library(specr)

# Currently, this code considers models with c1, c2, and c3 individually,
# no controls, and all three together.
results <- run_specs(
  df = dplyr::mutate(example_data, c3=runif(dplyr::n())), 
  y = c("y1", "y2"), 
  x = c("x1", "x2"), 
  model = c("lm"), 
  controls = c("c1", "c2", "c3")
)
dplyr::distinct(results, controls)
#> # A tibble: 5 x 1
#>   controls     
#>   <chr>        
#> 1 c1 + c2 + c3 
#> 2 c1           
#> 3 c2           
#> 4 c3           
#> 5 no covariates

# But what if these models with only one control variable are
# not in my set of "all plausible specifications"?
# Maybe I would consider c1 + c2 or c1 + c3.
results2 <- run_specs(
  df = dplyr::mutate(example_data, c3=runif(dplyr::n())), 
  y = c("y1", "y2"), 
  x = c("x1", "x2"), 
  model = c("lm"), 
  controls = list(c("c1", "c2"), c("c1", "c3"))
)
#> Error in model.frame.default(formula = "y1 ~ x1 + c(\"c1\", \"c2\") + c(\"c1\", \"c3\")", : variable lengths differ (found for 'c("c1", "c2")')
```

**Comment by masurp** [comment]
Dear Karl, 

in the current version, you can add groups of control variables (and their combination) as follows:

```{r}
library(specr)

results <- run_specs(
  df = dplyr::mutate(example_data, c3 = runif(dplyr::n())), 
  y = c("y1", "y2"), 
  x = c("x1", "x2"), 
  model = c("lm"), 
  controls = c("c1 + c2", "c1 + c3")  # note the different notation here
)
dplyr::distinct(results, controls)
#> # A tibble: 4 x 1
#>   controls         
#>   <chr>            
#> 1 c1 + c2 + c1 + c3
#> 2 c1 + c2          
#> 3 c1 + c3          
#> 4 no covariates  
```
As you can see, the function produces also the combination of the "combinations". You would need to remove this specification afterwards, if it doesn't make sense to you. 

We have considered including all combinations of controls, but as you said that increases the amount of specifications considerably (and for a standard routine potentially unnecessarily). I'll have to think about this more and might add some more standardized procedures in the next version. 

Hope this helps!

**Comment by karldw** [comment]
Hi @masurp, 

Ah, that's very helpful, thank you! 

Another tool that might be useful is `purrr::cross_df` and its `.filter` argument, which could be used in place of `expand.grid` in `setup_specs` to drop specifications before they're run.
(If that change sounds useful, I would be happy to submit a PR in a few weeks.)

**Comment by maswiebe** [comment]
> results <- run_specs(
>   df = dplyr::mutate(example_data, c3 = runif(dplyr::n())), 
>   y = c("y1", "y2"), 
>   x = c("x1", "x2"), 
>   model = c("lm"), 
>   controls = c("c1 + c2", "c1 + c3")  # note the different notation here
> )
> plot_specs(results)

One problem with this approach is that the graph doesn't recognize "c1+c2" or "c1+c3" as separate groups in the 'controls' section. Instead, they get lumped together as 'all covariates':
![image](https://user-images.githubusercontent.com/8338689/108104683-75b5d200-7040-11eb-805d-13842e6816ff.png)

**Comment by masurp** [comment]
Hi,

run_specs() no longer puts them together in the newest development version. Please install the latest version, and it should print them all separately. Will push to CRAN soon.

Best,
Philipp

**Comment by maswiebe** [comment]
Great, that works!

**Comment by akarlinsky** [comment]
I just found out on my own that I can include "groups" using this notation and it's very useful. Can this be added to the guides on the website?
