### ISSUE TITLE
Error when using `subsets` argument in `run_specs`

### ISSUE THREAD

**Issue by cortrudolph** [masurp/specr#12]
When running the example:

results<- run_specs(df = example_data, 
                     y = c("y1", "y2"), 
                     x = c("x1", "x2"), 
                     model = c("lm", "lm_gauss"), 
                     controls = c("c1", "c2"), 
                     subsets = list(group1 = unique(example_data$group1),
                                    group2 = unique(example_data$group2)))

I get the following error:

`Error in get(as.character(..2)) : object '1' not found`

This occurs with my own code and with the example in the vignette.

**Comment by cortrudolph** [comment]
Resolved by installing development version.

**Comment by masurp** [comment]
Hi Cort, 
I was not able to reproduce your error (i.e. neither with the CRAN nor the development version). Did you install all dependencies of the package?

**Comment by cortrudolph** [comment]
Hi Philipp,

Thank you for looking into this! The error resolved once I installed the development version (and all of the associated dependencies), so I assume this was tied up in a dependency issue on my end.

Cheers,
Cort.

**Comment by masurp** [comment]
Great! Glad that it works now!
