### ISSUE TITLE
Error message in Specr

### ISSUE THREAD

**Issue by ErinMacdonald** [masurp/specr#13]
Hi there, 

When I try to run through the analysis in the specr package using the ```example_data``` or my own data, everything is fine until I try the ```run_specs``` command, in which I get the following error message:

```
> results <- run_specs(df = example_data, 
+                      y = c("y1", "y2"), 
+                      x = c("x1", "x2"), 
+                      model = c("lm", "lm_gauss"), 
+                      controls = c("c1", "c2"), 
+                      subsets = list(group1 = unique(example_data$group1),
+                                     group2 = unique(example_data$group2)))
Error: Problem with `mutate()` input `..1`.
✖ Column `obs` not found in `.data`
ℹ Input `..1` is `.data$obs`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr_error>
Problem with `mutate()` input `..1`.
✖ Column `obs` not found in `.data`
ℹ Input `..1` is `.data$obs`.
Backtrace:
  1. specr::run_specs(...)
 33. dplyr:::stop_error_data_pronoun_not_found(...)
 34. dplyr:::stop_dplyr(index, dots, fn, problem = msg, .dot_data = TRUE)
> 
```

If you have any idea why this error is coming up or how to solve the issue that would be greatly appreciated. Thanks!

Erin

**Comment by masurp** [comment]
Hey Erin,

Have you tried to install all dependencies?

install.packages(“spear”, dep = T)

From the error message, it seems that a function might be missing.
Let me know if this fixes the problem.

best
Philipp


—
Dr. Philipp K. Masur

Johannes Gutenberg University Mainz
Department of Communication
Jakob-Welder-Weg 12
55128 Mainz

mail: philipp.masur@uni-mainz.de<mailto:philipp.masur@uni-mainz.de>
phone: (+49)6131 39 37253

http://www.kom.ifp.uni-mainz.de
http://www.philippmasur.de

On Aug 14, 2020, at 8:07 PM, ErinMacdonald <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi there,

When I try to run through the analysis in the specr package using the example_data or my own data, everything is fine until I try the run_specs command, in which I get the following error message:

> results <- run_specs(df = example_data,
+                      y = c("y1", "y2"),
+                      x = c("x1", "x2"),
+                      model = c("lm", "lm_gauss"),
+                      controls = c("c1", "c2"),
+                      subsets = list(group1 = unique(example_data$group1),
+                                     group2 = unique(example_data$group2)))
Error: Problem with `mutate()` input `..1`.
✖ Column `obs` not found in `.data`
ℹ Input `..1` is `.data$obs`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr_error>
Problem with `mutate()` input `..1`.
✖ Column `obs` not found in `.data`
ℹ Input `..1` is `.data$obs`.
Backtrace:
  1. specr::run_specs(...)
 33. dplyr:::stop_error_data_pronoun_not_found(...)
 34. dplyr:::stop_dplyr(index, dots, fn, problem = msg, .dot_data = TRUE)
>


If you have any idea why this error is coming up or how to solve the issue that would be greatly appreciated. Thanks!

Erin

**Comment by masurp** [comment]
Hey Erin, 

did you try installing the dependencies? Were you able to solve the problem?

Best,
Philipp

**Comment by ErinMacdonald** [comment]
Hi - so sorry for the delay, yes I was able to install the dependencies and that solved the problem. Thanks!

Erin
________________________________
