### ISSUE TITLE
Problem running PGLM function, even though PLM works fine

### ISSUE THREAD

**Issue by Toric-V** [masurp/specr#16]
Hi!

I work with panel data and have therefore specified a few different custom functions using the PLM package.  I input these as the models in run_specs() and it works just fine.

Example: 
```
within.plm.func <- function(formula, data) {
  plm(formula = formula, 
      data = data,
      model = "within")
}
```

I am, however, interested in running a negative binomial panel data analysis, and for that I need the PGLM package where I can specify the family = negbin, also.

```
Example: within.pglm.func <- function(formula, data) {
  pglm(formula = formula, 
      data = data,
      model = "within",
      family = negbin)
}
```

When I use this function in run_specs() I get the following error:

```
Error: Problem with `mutate()` input `coefs`.
x No tidy method recognized for this list.
i Input `coefs` is `map(.data$res, broom::tidy, conf.int = TRUE, conf.level = conf.level)`.

Run `rlang::last_error()` to see where the error occurred.
In addition: Der var 50 eller flere advarsler (brug warnings() for at se den første 50).
```

I have tried to install the development package, but the error persists.
If you know what causes it or how to fix it, I would greatly appreciate any input.

Best regards,
Toric

**Comment by masurp** [comment]
Dear Toric,

run_specs() uses `broom::tidy()` to extract relevant model parameters and `broom::glance()` to extract relevant fit indices. Although both support a long list of models, it might be possible that they don't work with the model class created by the PGLM package. The error "x No tidy method recognized for this list." seems to indicate this. We try to make specr as flexible as possible, but there is no way to anticipate all types of models/model classes. 

You could try to load the package `broom.mixed` which supports further model classes and overwrites the `tidy()` and the `glance()` function in `run_specs()`. If this doesn't work, I am afraid that specr might currently not support models from the PGLM package. 

Let me know if loading broom.mixed works.

Best
Philipp

**Comment by Toric-V** [comment]
Hi again,

Thanks for the speedy reply. Unfortunately loading broom.mixed did not work, but it is good to know why the error occured. Thank you for the help!

Best regards,
Toric
