### ISSUE TITLE
Problem treating x´s as pairs

### ISSUE THREAD

**Issue by Toric-V** [masurp/specr#17]
Hi!

I am interested in running a specification curve based on a multilevel model in which I use the within centered x variable as well as the cluster mean. Therefore I would like for specr to treat my two variables: within_centered and cluster_mean as x´s that are always present together.

Looking at the [response to issue 11](https://github.com/masurp/specr/issues/11) I figured that the below code might do the trick.

```
results <- run_specs(df = centered,
                      y = c("y"),
                      x = c("within_centered + cluster_mean"), 
                      model = c("lmer_ri_1"),
                      controls = c(var1, var2, var3),
                      keep.results = T)
```

The results of this code is however an empty dataframe. 
![image](https://user-images.githubusercontent.com/76000523/102638664-29d9d000-4158-11eb-8973-14aa60e6c9e0.png)

Do you know why? And is it possible to do what I am intending?

Best regards,
Toric

**Comment by masurp** [comment]
Dear Toric,

the way you specified the code is not how specr works. In other words, you can enter a term for the argument x that does not represent a column in the original data frame. There is basically only one way to do what you want to do:

You need to add both of them as independent variable and as control variables. This will estimate the desired models, but also additional (perhaps non-reasonable) specifications (e.g., only within_centered without cluster_mean as control). But this should not be a cause for concerns as you can easily filter out all non-reasonable specifications afterwards. 

Best,
Philipp
