### ISSUE TITLE
Request: order by specification

### ISSUE THREAD

**Issue by maswiebe** [masurp/specr#19]
[speccurve](https://github.com/hhsievertsen/speccurve) for Stata allows you to order the plot by specification, instead of coefficient size:
![image](https://user-images.githubusercontent.com/8338689/108114742-0e068380-704e-11eb-906b-f5ad4c476702.png)

This would be a nice feature to have.

**Comment by masurp** [comment]
Hey maswiebe,

this is a good point. Will think about including a respective argument in future versions of plot_specs(). For the time being, you try some simple code like this:

```
library(specr)
library(tidyverse)

results <- run_specs(df = example_data,
                     y = c("y1", "y2"),
                     x = c("x1", "x2"),
                     model = c("lm"),
                     controls = c("c1", "c2"),
                     subsets = list(group1 = unique(example_data$group1),
                                    group2 = unique(example_data$group2)))

p1 <- results %>%
  arrange(controls, estimate) %>%
  mutate(specifications = 1:nrow(.)) %>%
  ggplot(aes(x = specifications, y = estimate, ymin = conf.low, ymax = conf.high)) +
  geom_pointrange() +
  theme_classic()

p2 <- results %>%
  arrange(controls, estimate) %>%
  mutate(specifications = 1:nrow(.)) %>%
  tidyr::gather(key, value, controls) %>% 
  ggplot(aes(x = specifications, y = value)) + 
  geom_point(shape = 124, size = 3.35) + 
  theme_classic()

plot_specs(plot_a = p1, 
           plot_b = p2)
```

![Rplot01](https://user-images.githubusercontent.com/15741245/108118602-e2f85000-709e-11eb-9412-6d5e3293b5ca.png)

As the result frame includes all information, some tiny adjustments to this example code should do the job, no?

Best,
Philipp

**Comment by maswiebe** [comment]
Thanks, that's helpful.

**Comment by masurp** [comment]
The new development version 1.0.0 (which will be pushed to CRAN soon) allows to do this as follows:

```
# Load package
library(specr)

# Setup specifications
specs <- setup(example_data,
                     y = c("y1", "y2"),
                     x = c("x1", "x2"),
                     model = "lm",
                     distinct(example_data, group1),
                     distinct(example_data, group2),
                     controls = c("c1", "c2"))

# Run analysis
results <- specr(specs)

# Plot grouped by e.g. "controls"
plot(results, group = controls)
```
![Rplot01](https://user-images.githubusercontent.com/15741245/212647217-8f89f428-2c51-4622-9e60-53be7790c387.png)
