### ISSUE TITLE
Singleton control set produces duplicates

### ISSUE THREAD

**Issue by maswiebe** [masurp/specr#20]
When the control set is a singleton, run_specs() outputs duplicates. 
```
library(dplyr)

results <- run_specs(
  df = example_data,
  y = c("y1"),
  x = c("x1"),
  model = c("lm"),
  controls = c("c1")
  # controls = c("c1","c2")
)
plot_specs(results,choices=c("x","y","controls"))
distinct(results,across(x:subsets)) # grab distinct rows
```
My guess is that it's doing the combination category (ie, c1+c1), which is the same as c1 by itself.

**Comment by masurp** [comment]
Thanks for letting us know. I missed this. Fixed it in the newest development version. 

Best,
Philipp
