### ISSUE TITLE
Run a list of predefined specifications

### ISSUE THREAD

**Issue by hp2500** [masurp/specr#23]
Hi there, 

I am trying to run a specification curve analysis on a predefined list of specifications that I generate using my own code. This list is a subset of the combinations of a very large set of variables. Theoretically, I could run analyses for my list of specifications by running all combinations and then subsetting the output to include only the relevant specifications, but I think that this is computationally prohibitive. Ideally, I would like to use a dataset of the same format as the output of the setup_specs() function as input for the run_specs() function. This would provide more control with respect to the list of specifications that are run. Is this currently possible or should I fork and modify the code? 

I am thinking about something like this:

```{R}
df_specs <- my_own_setup_specs(...)
run_specs(df_specs) 
```
Guidance would be much appreciated!

**Comment by masurp** [comment]
Hi, 

this is currently not possible. If you have a potential solution for this, feel free to fork and create a pull request. Would love to have a look at it. 

best,
Philipp

**Comment by masurp** [comment]
Will be solved in a new version I hope to push soon.

**Comment by masurp** [comment]
New development version 1.0.0 is now available via github. Check out the website for learning how to use the new framework: https://masurp.github.io/specr/index.html

Very simply speaking, it works like this. But setting up specifications beforehand, opens up completely new possibilites. 

```
# Load package ----
library(specr)

# Setup Specifications ----
specs <- setup(data = example_data, 
               y = c("y1", "y2"), 
               x = c("x1", "x2"), 
               model = c("lm"), 
               distinct(example_data, group1),
               distinct(example_data, group2),
               controls = c("c1", "c2"))

# Run Specification Curve Analysis ----
results <- specr(specs)

# Plot Specification Curve ----
plot(results)
```
