### ISSUE TITLE
Bug: `plot_specs()` plot is uninterpretable if there are many covariates.

### ISSUE THREAD

**Issue by gserapio** [masurp/specr#28]
Thank you for your work on this package and sharing it with everyone.

I'm running in to an issue where I have a long list of control variables, which causes the output of `plot_specs()` to be cut off and uninterpretable. See reprex below, but imagine that there at least 20 more covariates after the 3 listed. Would it be possible to rename this long label for controls as simply "all covariates", to correspond with the label "no covariates"?

``` r
library(tidyverse)
library(specr)

results_test <- 
  run_specs(iris,
            x = c("Sepal.Length"),
            y = c("Sepal.Width"),
            controls = c("Petal.Length", "Petal.Width", "Species"),
            model = "lm")

plot_specs(results_test)
```

![](https://i.imgur.com/8srnFvp.png)

<sup>Created on 2022-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by akarlinsky** [comment]
run_specs returns a tidy dataframe that you can manipulate as any df. 
Since "all covariates" will be the longest "controls" column, here's a quick and easy code to achieve your goal:
`
results_test %>% 
  mutate(controls_length = nchar(controls), 
         controls = if_else(controls_length == max(controls_length), "All Controls",controls))  
`

**Comment by gserapio** [comment]
Great point, I will do this. Thanks so much!

**Comment by gserapio** [comment]
Sorry to re-open this: Wasn't it the case that version `0.2.1` labels all combinations of controls as "all covariates" by default, without extra code to modify your `run_specs` data frame?

**Comment by masurp** [comment]
Hi, you're right. The CRAN version still does this automatically. I honestly don't remember why I changed this in the new development version. Perhaps someone ask for showing the raw formula!?

I have to think about this. Perhaps I'll just add a extra argument for switching between the two options. For now, I believe @akarlinsky's suggestion should work fine.

**Comment by masurp** [comment]
The new version allows to setup all specifications before actually running the analyses. This is done by using the function `setup()` in which you can specify `simplify = TRUE`. In that case, it sets up control variables as it was done in the earlier versions: none, each individually, altogether and labels them "no covariates", name of each variables, and "all covariates". If `simplify = FALSE`, it plots all combinations and only relables "no covariates". I decided to keep it this way in the non-simplified version, as it is really unforeseeable what users would like to received in their result table in this regard. 


```
# Setup specification that include all combinations of covariates
specs1 <- setup(data = example_data,
               x = c("x1", "x2"),
               y = c("y1", "y2"),
               model = "lm",
               controls = c("c1", "c2", "c3", "c4"))  # simply providing a vector of control variables

# Setup secifications that include only no covariates, each individually, and all together
specs2 <- setup(data = example_data,
               x = c("x1", "x2"),
               y = c("y1", "y2"),
               model = "lm",
               controls = c("c1", "c2", "c3", "c4"),
               simplify = TRUE)   # Difference to specs1!

# Check
distinct(specs1$specs, controls)
```
```
## # A tibble: 16 × 1
##    controls         
##    <chr>            
##  1 no covariates    
##  2 c1               
##  3 c2               
##  4 c3               
##  5 c4               
##  6 c1 + c2          
##  7 c1 + c3          
##  8 c1 + c4          
##  9 c2 + c3          
## 10 c2 + c4          
## 11 c3 + c4          
## 12 c1 + c2 + c3     
## 13 c1 + c2 + c4     
## 14 c1 + c3 + c4     
## 15 c2 + c3 + c4     
## 16 c1 + c2 + c3 + c4
```

```
distinct(specs2$specs, controls)
```

```
## # A tibble: 6 × 1
##   controls      
##   <chr>         
## 1 no covariates 
## 2 c1            
## 3 c2            
## 4 c3            
## 5 c4            
## 6 all covariates
```
