### ISSUE TITLE
Don't get "no covariates" in fixed effects regression

### ISSUE THREAD

**Issue by maswiebe** [masurp/specr#30]
I'm using fixest::feols to run a fixed effects regression, but the "no covariates" row doesn't show up.

```
library(dplyr)
library(fixest)
library(specr)

test_formula <- function(formula,data) {
  formula <-as.formula(paste0(formula, "|group1")) # fixed effects for group1
  feols(formula,data)
}
results <- run_specs(
  df = example_data,
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  model = 'test_formula',
  controls = c("c1", "c2")
)

plot_specs(results)

```

![image](https://user-images.githubusercontent.com/8338689/192896201-5f9d190e-e3ea-43d7-8c38-887b7d0051aa.png)

I notice that it works if the regression formula includes a variable before the fixed effects section:
```
test_formula2 <- function(formula,data) {
  formula <-as.formula(paste0(formula, "+ c3 |group1")) # control for c3 in all specifications
  feols(formula,data)
}
results2 <- run_specs(
  df = dplyr::mutate(example_data, c3 = runif(dplyr::n())),
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  model = 'test_formula2',
  controls = c("c1", "c2")
)

plot_specs(results2)
```
![image](https://user-images.githubusercontent.com/8338689/192897130-42d52a43-5847-4800-8c69-f85b8ee451aa.png)

**Comment by masurp** [comment]
I cannot recreate the error using the newest development version of specr (v1.0.0)

```
library(dplyr)
library(fixest)
library(specr)

test_formula <- function(formula,data) {
  formula <-as.formula(paste0(formula, "|group1")) # fixed effects for group1
  feols(formula,data)
}
results <- run_specs(
  df = example_data,
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  model = 'test_formula',
  controls = c("c1", "c2")
)

plot_specs(results)
```

![Rplot](https://user-images.githubusercontent.com/15741245/212672836-136e08f0-e4e5-4184-b4e3-098753771914.png)


Also using the new framework, it produces an appropriate plot:

```
specs <- setup(
  data = example_data,
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  model = 'test_formula',
  controls = c("c1", "c2")
)


results <- specr(specs)

plot(results)
````
![Rplot02](https://user-images.githubusercontent.com/15741245/212673131-72bde2a2-4ebc-4e0b-8e14-898c149c0fcd.png)
