### ISSUE TITLE
Testing the effect of an interaction term

### ISSUE THREAD

**Issue by arranjdavis** [masurp/specr#35]
Hello, love the package so far - thanks for your work on it! 

I want to add an interaction term to my specification curve analysis. How do I do this? 

My current set-up is as follows.

```
setup(data = dat,
           x = c("lonely_mostly_or_not", "hinctnta"),
           y = c("mean_p_eff_cgg_dpr_z", "mean_p_eff_dpr_z"),
           model = c("lmer"),
           controls = c("agea", "icgndra", "jbexpnt", "health_problems"),
           add_to_formula = "(1 | nuts1)") 
```

I want to test the interaction between `lonely_mostly_or_not` and `hinctnta`. I have tried specifying it as both an `x` variable (`lonely_mostly_or_not * hnctnta`) and I've tried to add it to the `add_to_formula` argument (`lonely_mostly_or_not * hnctnta + (1 | nuts1)`). Neither seemed to work, and I didn't see anything about this in the documentation (but I am probably missing something obvious!).

Thanks for your help!

**Comment by arranjdavis** [comment]
Hi again,

Okay, so I can now add an interaction term (with `x = c("lonely_mostly_or_not:hinctnta")`). However, this does not force the main effects of `lonely_mostly_or_not` and `hinctnta` to be included in the model. Is there a way to 'force' `specr` to include both main effects and their interaction for all models in the specification curve analysis? 

No worries if not, I can just create a couple calls to `specr` with different combinations of the main effect and interaction terms as either the `x` variable or `controls` and then just select the models that contained all three of these variables (i.e., `lonely_mostly_or_not`, `hinctnta`, and `lonely_mostly_or_not:hinctnta`) for the final presentation of the specification curve analysis.

Thanks for your help with this, and for the package more generally - it has been great to use!

**Comment by masurp** [comment]
Hi,

Including interaction terms is not trivial. I honestly haven't really thought about it too much yet. If you are interested in a categorical or nominal moderator, it might be easier to explore its effect simply by treating it as a grouping variable and add it as subset. 

That said, I played around a little and came up with this:

```

library(specr)

# Create specifications without interaction term
specs_without_interaction <- setup(
  data = example_data,
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  controls = c("x1", "x2"),
  model = "lm")

# Create specifications with interaction term by using "add_to_formula"
specs_with_interaction <- setup(
  data = example_data,
  y = c("y1", "y2"),
  x = c("x1", "x2"),
  controls = c("x1", "x2"),
  model = "lm",
  add_to_formula = "x1:x2") 

# Extract specifications and bind together
specs <- rbind(
  as_tibble(specs_without_interaction) %>%
    mutate(interaction = "no"),
  as_tibble(specs_without_interaction) %>%
    mutate(interaction = "yes")
)

# Run specification curve analysis on the tibble (need to provide data!)
results <- specr(specs, data = example_data) 

# The resulting tibble contains all estimates and can be plotted with the "old" function:
plot_specs(results, 
           choices = c("x", "y", "interaction"))

```

<img width="573" alt="Screenshot 2023-10-10 at 09 53 20" src="https://github.com/masurp/specr/assets/15741245/a4015064-094d-4d26-8099-239a6672bb7c">

The analysis thus now includes models without the interaction term and with interaction term, always extract the "conditional" effect of the independent variable... 

It does not show the coefficient of the interaction term itself. If you want that, you could think about including the entire model object in your specr output (see: https://masurp.github.io/specr/articles/invest-spec.html). Then you have all information that you can want and just have to figure out a way to plot it....

**Comment by arranjdavis** [comment]
Hi Philipp,

Thanks for taking the time to respond. My main concern was that I was missing something trivial that would allow me to add the interaction term.

That doesn't seem to be the case (and now I can see why!), so what you've suggested sounds like a perfectly fine work around. 

I had been toying with a similar idea where I create three specifications as follows.

```
specifications1 = setup(data = dat,
                        x = c("lonely_mostly_or_not:hinctnta"),
                        y = c("mean_p_eff_cgg_dpr_z", "mean_p_eff_dpr_z"),
                        model = c("lmer"),
                        controls = c("lonely_mostly_or_not", "hinctnta","agea", "icgndra", "jbexpnt", "health_problems"),
                        add_to_formula = "(1 | nuts1)") 

specifications2 = setup(data = dat,
                        x = c("lonely_mostly_or_not"),
                        y = c("mean_p_eff_cgg_dpr_z", "mean_p_eff_dpr_z"),
                        model = c("lmer"),
                        controls = c("hinctnta","agea", "icgndra", "jbexpnt", "health_problems"),
                        add_to_formula = "lonely_mostly_or_not:hinctnta + (1 | nuts1)") 

specifications3 = setup(data = dat,
                        x = c("hinctnta"),
                        y = c("mean_p_eff_cgg_dpr_z", "mean_p_eff_dpr_z"),
                        model = c("lmer"),
                        controls = c("lonely_mostly_or_not","agea", "icgndra", "jbexpnt", "health_problems"),
                        add_to_formula = "lonely_mostly_or_not:hinctnta + (1 | nuts1)") 
```

I then just need to subset the specifications or the results (after running `specr`) to include only those models that included as controls both variables involved in the interaction (`lonely_mostly_or_not` and `hinctnta`) for `specifications1`, and that included the other variable involved in the interaction (main one added as `x`) that was added as a control for `specifications2` and `specifications3` (since the interaction was included in all models using the `add_to_formula` argument for these specifications).

As I understand, this will then give me enough information to create specification curves for both of the predictor variables (`lonely_mostly_or_not` and `hinctnta`) and their interaction (`lonely_mostly_or_not:hinctnta`).

You can mark this as closed now (if all of that makes sense!). There certainly seem to be a few options to do what I'd like, and hopefully this is helpful for others, too. Thanks again!

**Comment by masurp** [comment]
Perfect. I will continue thinking about this, but glad that some of these approaches work!
