### ISSUE TITLE
How to customise the colours in specr plots

### ISSUE THREAD

**Issue by al-joseph** [masurp/specr#37]
Thank you once again for building this great package. I have read the [Alternative way to visualize specification results](https://masurp.github.io/specr/articles/custom-plot.html#comprehensive-standard-visualization) section, but I want to know how to change the colours in type (i.e. curve, results, and samplesizes) as part of the 'standard' output plot. 

For curve and results, I did `+ scale_color_manual(values = c("#HEXCODE"))` which worked great. However, for samplesize, although it looks like a geom_bar, I am not sure why scale_fill_manual (or equally scale_color_manual) isn't working? It just returns the default grey colour.

**Comment by masurp** [comment]
It is a bar chart and grey is passed as a bar fill characteristics. `scale_fill_manual()` thus unfortunately won't work. I suggest to simply plot it manually:

```
library(tidyverse)
library(specr)

as_tibble(results) |> 
  arrange(-estimate) |> 
  mutate(specifications = 1:n()) |> 
  ggplot(aes(x = specifications,
             y = fit_nobs)) +
  geom_bar(stat = "identity",
           fill = "steelblue",                # change color here to your liking!
           size = .2) +
  theme_minimal()
```
![Rplot](https://github.com/masurp/specr/assets/15741245/3cd28fb6-e8a6-460a-8648-6fc282c6a73a)
