### ISSUE TITLE
Variance decomposition

### ISSUE THREAD

**Issue by mscharkow** [masurp/specr#5]
As an alternative visualization/analysis, provide variance components for the specs and the variability of a predefined parameter.

**Comment by masurp** [comment]
I pushed two functions in this regard. 

1. variance_specs(): Allows to estimate the ICCs from the results frame.
2. plot_variance(): Plots ICCs as bar plot. 

Can still be improved upon. Just added the scripts to provide a first version.

**Comment by masurp** [comment]
Test brms alternative for variance components.

**Comment by masurp** [comment]
Current solution is exemplified here:
https://masurp.github.io/specr/articles/decompose_var.html
